name: Email to Printer

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 07:00 UTC (09:00 Madrid time if DST is in effect)
  workflow_dispatch:

jobs:
  run-email2printer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run email2printer script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          PRINTER_EMAIL: ${{ secrets.PRINTER_EMAIL }}
        run: |
          python email2printer.py
